const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../sw.js'),'utf8');
function html(text='installed index',redirected=false){const r=new Response(text,{headers:{'content-type':'text/html; charset=utf-8','content-encoding':'gzip','content-length':'999'}});if(redirected)Object.defineProperty(r,'redirected',{value:true});return r;}
function sw(options={}){
 const handlers={},deleted=[],entries=new Map([['./index.html',html('installed index',options.redirected)]]);let fetched=0,claimed=0,skipped=0;
 const ctx=vm.createContext({URL,Response,Headers,Promise,AbortController,setTimeout,clearTimeout,self:{location:{origin:'https://player.test',href:'https://player.test/sw.js'},addEventListener:(type,fn)=>handlers[type]=fn,skipWaiting:async()=>{skipped++},clients:{claim:async()=>{claimed++}}},caches:{open:async()=>{if(options.cacheFailure)throw new Error('cache unavailable');return {match:async key=>options.missing?undefined:entries.get(key),addAll:async assets=>{for(const a of assets)assert.ok(fs.existsSync(path.join(__dirname,'..',a.split('?')[0])))},put:async(key,value)=>{if(options.putFailure)throw new Error('quota');entries.set(key,value)}}},keys:async()=>['lv-player-app-old','lv-player-app-v1-9-1-navigation-hotfix','lv-media-bundle-v1-8-0'],delete:async key=>{if(options.deleteFailure)throw new Error('cannot delete');deleted.push(key)}},fetch:async()=>{fetched++;if(options.offline)throw new Error('offline');if(options.badNetworkResponse)return new Response('missing',{status:404});return html('network index',true)}});
 vm.runInContext(options.source || source,ctx);return {ctx,handlers,entries,deleted,get fetched(){return fetched},get claimed(){return claimed},get skipped(){return skipped}};
}
async function navigate(h){let result;const request={method:'GET',url:'https://player.test/?store=sushihiromi&id=lv039',mode:'navigate',redirect:'manual'};h.handlers.fetch({request,respondWith:p=>result=p});const response=await result;
 // Fetch Standard's service-worker response check: redirect history cannot be replayed for manual navigation.
 if(request.redirect!=='follow' && response.redirected)throw new Error('navigation network error: redirected response');return response;
}
test('previous navigation branch fails the same redirected-response check',async()=>{const h=sw({redirected:true,source:fs.readFileSync(path.join(__dirname,'fixtures/sw-v190-navigation.txt'),'utf8')});await assert.rejects(navigate(h),/navigation network error: redirected response/);});
test('redirected cached HTML is normalized for a manual navigation',async()=>{const h=sw({redirected:true});const r=await navigate(h);assert.equal(r.redirected,false);assert.equal(await r.text(),'installed index');assert.equal(h.fetched,0);});
test('first install normalizes redirected document before activation',async()=>{const h=sw({redirected:true});let work;h.handlers.install({waitUntil:p=>work=p});await work;assert.equal(h.entries.get('./index.html').redirected,false);assert.equal(h.skipped,1);});
test('HTML response drops stale transport compression and length',async()=>{const h=sw({redirected:true});const r=await navigate(h);assert.equal(r.headers.get('content-encoding'),null);assert.equal(r.headers.get('content-length'),null);assert.match(r.headers.get('content-type'),/text\/html/);});
test('cache access failure falls back to normalized network HTML',async()=>{const h=sw({cacheFailure:true});const r=await navigate(h);assert.equal(await r.text(),'network index');assert.equal(r.redirected,false);assert.equal(h.fetched,1);});
test('missing cached HTML follows the hosting redirect safely',async()=>{const h=sw({missing:true});const r=await navigate(h);assert.equal(await r.text(),'network index');assert.equal(r.redirected,false);});
test('offline with installed HTML continues using local document',async()=>{const h=sw({offline:true,redirected:true});assert.equal(await (await navigate(h)).text(),'installed index');assert.equal(h.fetched,0);});
test('offline without readable cache returns a local recovery document',async()=>{const h=sw({cacheFailure:true,offline:true});const r=await navigate(h);assert.equal(r.status,200);assert.equal(r.headers.get('x-lv-recovery'),'document-unavailable');assert.match(await r.text(),/다시 연결/);});
test('failed network HTTP status is not promoted to normal Player HTML',async()=>{const h=sw({missing:true,badNetworkResponse:true});const r=await navigate(h);assert.equal(r.headers.get('x-lv-recovery'),'document-unavailable');});
test('activation removes only old application caches and keeps media',async()=>{const h=sw();let work;h.handlers.activate({waitUntil:p=>work=p});await work;assert.deepEqual(h.deleted,['lv-player-app-old']);assert.equal(h.claimed,1);});
test('cache cleanup failure does not prevent new worker control',async()=>{const h=sw({deleteFailure:true});let work;h.handlers.activate({waitUntil:p=>work=p});await work;assert.equal(h.claimed,1);});
test('API and version lookups remain outside document caching',()=>{const h=sw();for(const pathname of ['/api/player-state','/version.json'])h.handlers.fetch({request:{method:'GET',url:'https://player.test'+pathname,mode:'cors'},respondWith:()=>assert.fail('intercepted live endpoint')});});
test('error, opaque, partial and non-HTML responses cannot become Player documents',()=>{const h=sw();for(const expression of ["Response.error()","({ok:true,status:200,type:'opaque'})","new Response('partial',{status:206,headers:{'content-type':'text/html'}})","new Response('data',{headers:{'content-type':'application/json'}})"])assert.throws(()=>vm.runInContext('navigationDocument('+expression+')',h.ctx),/unavailable|not HTML/);});
test('failed install cannot activate an incompletely cached application',async()=>{const h=sw({putFailure:true,redirected:true});let work;h.handlers.install({waitUntil:p=>work=p});await assert.rejects(work,/quota/);assert.equal(h.skipped,0);});
test('unexpected cross-origin network document returns recovery HTML',async()=>{const h=sw({missing:true});h.ctx.fetch=async()=>{const response=html('other host');Object.defineProperty(response,'url',{value:'https://other.test/login'});return response;};assert.equal((await navigate(h)).headers.get('x-lv-recovery'),'document-unavailable');});
test('asset cache write failure still returns the successful network response',async()=>{const h=sw({putFailure:true});let result;h.handlers.fetch({request:{method:'GET',url:'https://player.test/runtime.js?v=1.9.1',mode:'cors'},respondWith:p=>result=p});assert.equal((await result).status,200);assert.equal(h.fetched,1);});
