const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {integrated}=require('./app.test.cjs');
const {FaultLedger,Tombstones,rightAllowed,blackActive}=require('../sync-runtime.js');
function storage(){const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}}
const f={side:'left',itemId:'left2',assetVersion:'bytes-v1',sourceUrl:'same.mp4',fileName:'left_2.mp4',attemptId:'a1'};
async function waitPlaying(h,side){for(let i=0;i<20&&h.run(`lanes.${side}.phase`)!=='playing';i++)await h.advance(500);assert.equal(h.run(`lanes.${side}.phase`),'playing')}
async function ready(){const h=integrated();await h.advance(6000);return h}
async function update(h,edit){edit(h.controller);h.controller.version=`${Number((h.controller.version||'1:1').split(':')[0])+1}:1`;h.run('syncCoordinator.wake(false)');await h.advance(3000)}
test('full v3 boot uses a CORS-simple sync only and starts both lanes with sealed cached files',async()=>{const h=await ready();assert.equal(h.run('lanes.left.phase'),'playing');assert.equal(h.run('lanes.right.phase'),'playing');assert.ok(h.calls.some(c=>c.path==='/api/player-sync'));assert.equal(h.calls.find(c=>c.path==='/api/player-sync').init.headers['content-type'],'text/plain;charset=UTF-8');assert.equal(h.calls.filter(c=>['/api/heartbeat','/api/player-status','/api/player-state','/api/player-control','/api/player-command','/api/black-mode','/api/notice-active','/api/player-errors'].includes(c.path)).length,0)});
test('unchanged regular sync downloads no manifest or media and does not reset lane playback',async()=>{const h=await ready(),before=h.calls.filter(c=>c.path!=='/api/player-sync').length;h.run('syncCoordinator.wake(false)');await h.advance(1000);assert.equal(h.calls.filter(c=>c.path!=='/api/player-sync').length,before);assert.equal(h.run('lanes.right.phase'),'playing')});
test('local health and stage changes cannot create more polling timers',async()=>{const h=await ready(),before=h.calls.length;for(let i=0;i<100;i++)h.run('requestHealthReport()');await h.advance(30000);assert.equal(h.calls.length,before)});
test('left-only playlist update preserves right bytes and generation except normal completions',async()=>{const h=await ready(),rightGets=h.calls.filter(c=>c.path==='/right.mp4').length;await update(h,c=>{c.manifest.playlists.left=[{...c.manifest.playlists.left[0],id:'new',url:'https://cdn.test/new.mp4'}]});assert.equal(h.run('state.leftItems[0].id'),'new');assert.equal(h.calls.filter(c=>c.path==='/right.mp4').length,rightGets);assert.equal(h.run('lanes.right.phase'),'playing')});
test('reorder reuses all cached files with zero media GETs',async()=>{const h=await ready();await update(h,c=>c.manifest.playlists.left.push({...c.manifest.playlists.left[0],id:'two',url:'https://cdn.test/two.mp4'}));const count=h.calls.filter(c=>c.path.endsWith('.mp4')).length;await update(h,c=>c.manifest.playlists.left.reverse());assert.equal(h.calls.filter(c=>c.path.endsWith('.mp4')).length,count);assert.equal(h.run('state.leftItems[0].id'),'two')});
test('replacement downloads only new originals and logically removes old files',async()=>{const h=await ready();await update(h,c=>{const a=c.manifest.playlists.left[0];c.manifest.playlists.left=[a,{...a,id:'B',url:'https://cdn.test/B.mp4'},{...a,id:'C',url:'https://cdn.test/C.mp4'}]});const n=h.calls.length;await update(h,c=>{const [a,,cc]=c.manifest.playlists.left;c.manifest.playlists.left=[a,{...a,id:'D',url:'https://cdn.test/D.mp4'},cc,{...a,id:'E',url:'https://cdn.test/E.mp4'}]});assert.deepEqual(h.calls.slice(n).filter(x=>x.path.endsWith('.mp4')).map(x=>x.path).sort(),['/D.mp4','/E.mp4']);assert.equal(h.run("state.leftItems.some(i=>i.id==='B')"),false)});
test('valid empty publication excludes content; missing/failed response retains cached playback',async()=>{const h=await ready();h.controller.apiResponse=u=>u.pathname==='/api/player-sync'?new Response('{}',{status:503}):null;h.run('syncCoordinator.wake(false)');await h.advance(1000);assert.equal(h.run('state.leftItems.length'),1);assert.equal(h.run('lanes.right.phase'),'playing')});
test('explicit delete is removed from live lane, active/previous journal and local schedule',async()=>{const h=await ready();await update(h,c=>{c.tombstones=[{asset_id:'left',asset_version:'*'}];c.manifest.playlists.left=[]});assert.equal(h.run('state.leftItems.length'),0);assert.equal(h.run("bundleJournal.read().active.left.some(i=>i.id==='left')"),false);assert.equal(h.run("tombstones.allows({id:'left'})"),false);assert.equal(h.run('lanes.right.phase'),'playing')});
test('offline replay remains independent and uses zero media downloads after first preparation',async()=>{const h=await ready(),gets=h.calls.filter(c=>c.path.endsWith('.mp4')).length;h.controller.offline=true;await h.advance(180000);assert.ok(h.run('playbackMetrics.completed')>20);assert.equal(h.calls.filter(c=>c.path.endsWith('.mp4')).length,gets);assert.equal(h.run('state.rightItems.length'),1)});
test('same-origin restart restores healthy cached playback even without the server',async()=>{const h=await ready();h.run('syncLease.release();syncCoordinator.stop()');const next=integrated({storage:h.storage,cacheSets:h.cacheSets,offline:true});await next.advance(5000);await waitPlaying(next,'left');await waitPlaying(next,'right')});
test('bad expected digest never commits partial data; unaffected right continues',async()=>{const h=await ready(),m=await h.run("LVIntegrity.inspect(new Blob(['wrong']).stream())");await update(h,c=>c.manifest.playlists.left=[{...c.manifest.playlists.left[0],id:'bad',url:'https://cdn.test/bad.mp4',integrity:m}]);assert.equal(h.run("state.leftItems.some(i=>i.id==='bad')"),false);assert.equal(h.run('lanes.right.phase'),'playing');assert.equal(h.run('delivery.phase'),'blocked')});
test('notice and black mode preserve separate suspension ownership',async()=>{const h=await ready();await h.run("showNoticeOverlay({id:'n',type:'image',mediaUrl:'https://cdn.test/n.jpg',durationSec:5,repeatMode:'once'},'remote-command')");h.run("setBlackMode(true,'test');hideNoticeOverlay()");assert.equal(h.run('lanes.left.phase'),'paused');h.run("setBlackMode(false,'off')");await h.advance(4000);await waitPlaying(h,'right')});
test('first fault / exclusion / same-file recovery survive persistence; duplicate attempt not counted twice',()=>{const s=storage(),l=new FaultLedger(s,'f');assert.equal(l.failure(f),true);assert.equal(l.failure(f),false);assert.equal(l.failure({...f,attemptId:'a2'}),false);assert.equal(l.exclude(f),true);assert.equal(l.exclude(f),false);const next=new FaultLedger(s,'f');assert.equal(next.snapshot()[0].count,2);assert.equal(next.recover({...f,itemId:'other'}),false);assert.equal(next.recover(f),true);assert.equal(next.snapshot()[0].status,'recovered')});
test('repeat failures aggregate without new detailed samples or first-fault events',()=>{const l=new FaultLedger(storage(),'f');let first=0;for(let i=0;i<20;i++)first+=l.failure({...f,attemptId:String(i)})?1:0;assert.equal(first,1);assert.equal(l.snapshot()[0].count,20);assert.equal(l.value.samples.length,1)});
test('ten-sample cap persists after acknowledgements; faults remain visible',()=>{const s=storage(),l=new FaultLedger(s,'f');for(let i=0;i<30;i++)l.failure({...f,itemId:'f'+i,attemptId:String(i)});assert.equal(l.value.samples.length,10);l.acknowledge(l.value.samples.map(x=>x.id));const next=new FaultLedger(s,'f');next.failure({...f,itemId:'extra'});assert.equal(next.value.samples.length,0);assert.equal(next.snapshot().filter(x=>x.status==='fault').length,31)});
test('active fault does not expire with seven-day detailed log retention',()=>{const l=new FaultLedger(storage(),'f'),now=Date.now();l.failure(f,now-8*86400000);assert.equal(l.snapshot(now).length,1);assert.equal(l.snapshot(now)[0].status,'fault')});
test('identical name, different asset version or lane retain separate error state',()=>{const l=new FaultLedger(storage(),'f');l.failure(f);l.failure({...f,side:'right'});l.failure({...f,assetVersion:'v2'});assert.equal(l.snapshot().length,3);l.recover(f);assert.equal(l.snapshot().filter(x=>x.status!=='recovered').length,2)});
test('tombstones survive old manifest and cannot be erased by an empty or older deletion list',()=>{const s=storage(),t=new Tombstones(s,'d');t.merge([{asset_id:'gone',asset_version:'*'}]);t.merge([]);assert.equal(new Tombstones(s,'d').allows({id:'gone'}),false);assert.equal(t.allows({id:'new'}),true)});
test('selected right permission stays cached offline, empty or invalid selection is denied',()=>{assert.equal(rightAllowed({targetMode:'selected',targetStores:['qa']},'qa'),true);assert.equal(rightAllowed({targetMode:'selected',targetStores:[]},'qa'),false);assert.equal(rightAllowed({targetMode:'selected',targetStores:['qa']},''),false);assert.equal(rightAllowed({targetMode:'broken'},'qa'),false)});
test('received immediate black expiry is locally honored without a server call',()=>{const now=Date.parse('2026-10-07T00:00:00Z');assert.equal(blackActive({immediate_active:1,immediate_until:'2026-10-07T00:01:00Z'},now),true);assert.equal(blackActive({immediate_active:1,immediate_until:'2026-10-07T00:01:00Z'},now+120000),false)});
test('overnight playlist uses start-day semantics',async()=>{const h=await ready();assert.equal(h.run("isScheduleActiveAt({days:[1],startTime:'22:00',endTime:'02:00'},new Date('2026-09-07T16:00:00Z'))"),true);assert.equal(h.run("isScheduleActiveAt({days:[1],startTime:'22:00',endTime:'02:00'},new Date('2026-09-06T16:00:00Z'))"),false)});
test('remote refresh executes once, preserves media, and keeps its command id',async()=>{const h=await ready();const before=await h.run('getMediaCache().then(c=>c.keys()).then(k=>k.length)');h.controller.command={command:'refresh',commandAt:'2026-10-07T00:00:00Z'};h.run('syncCoordinator.wake(false)');await h.advance(1500);assert.equal(h.run("readJsonStorage('lv-last-command-result',{}).commandAt"),'2026-10-07T00:00:00Z');assert.equal(await h.run('getMediaCache().then(c=>c.keys()).then(k=>k.length)'),before);assert.equal(await h.run("handleRemoteCommand([{id:CONFIG.deviceId,store:CONFIG.store}],{command:'refresh',commandAt:'2026-10-07T00:00:00Z'})"),false)});
test('native screenshot is requested once and is not falsely acknowledged as stored',async()=>{const h=await ready();let captured=0;h.ctx.LocalVisionNative={captureScreenshot:()=>captured++};h.controller.command={command:'screenshot',commandAt:'2026-10-07T00:01:00Z'};h.run('syncCoordinator.wake(false)');await h.advance(1000);assert.equal(captured,1);assert.equal(h.run("readJsonStorage('lv-last-command-result',{}).status"),'native-requested');h.run('syncCoordinator.wake(false)');await h.advance(1000);assert.equal(captured,1)});
test('missing bridge reports unsupported without retrying the same screenshot command forever',async()=>{const h=await ready();h.controller.command={command:'screenshot',commandAt:'2026-10-07T00:02:00Z'};h.run('syncCoordinator.wake(false)');await h.advance(1000);assert.equal(h.run("readJsonStorage('lv-last-command-result',{}).status"),'unsupported');assert.equal(await h.run("handleRemoteCommand([{id:CONFIG.deviceId,store:CONFIG.store}],{command:'screenshot',commandAt:'2026-10-07T00:02:00Z'})"),false)});
